name = "wtracker-web"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[containers]]
class_name = "MyContainer"
image = "./Dockerfile"
max_instances = 5

[[durable_objects.bindings]]
class_name = "MyContainer"
name = "MY_CONTAINER"

[exports.MyContainer]
type = "durable-object"
storage = "sqlite"

[observability]
enabled = true
