name = "wtracker-web" # IMPORTANTE: Debe coincidir EXACTAMENTE con el nombre en el Dashboard de Cloudflare
compatibility_date = "2024-04-05"

[build]
dockerfile = "./Dockerfile" # Ruta directa al archivo Docker local
